# Generated by Django 4.2.27 on 2026-03-04 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_acp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agenttask',
            new_name='acp_agent_t_status_faf97f_idx',
            old_name='acp_agent_t_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agenttask',
            new_name='acp_agent_t_agent_n_84ec5a_idx',
            old_name='acp_agent_t_agent_n_idx',
        ),
        migrations.RenameIndex(
            model_name='agenttask',
            new_name='acp_agent_t_created_a91561_idx',
            old_name='acp_agent_t_created_idx',
        ),
    ]
