# Generated by Django 4.2.27 on 2026-02-11 00:33

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('source', models.CharField(db_index=True, max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('ENQUEUED', 'Enqueued'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], db_index=True, default='RECEIVED', max_length=24)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
