# ============================================================================
# ARQUITETURA NOVA - app_whatsapp_gateway
# ============================================================================
# Generated migration for EvolutionInstance multi-tenant
# ============================================================================

# Generated by Django (manual migration)

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shopper_id', models.CharField(db_index=True, help_text='ID do Shopper (UUID do VitrineZap) - Multi-tenant', max_length=100)),
                ('instance_id', models.CharField(db_index=True, help_text="ID da instância na Evolution API (ex: 'shopper_123')", max_length=100, unique=True)),
                ('status', models.CharField(choices=[('creating', 'Criando'), ('opening', 'Abrindo'), ('open', 'Conectada'), ('close', 'Desconectada'), ('connecting', 'Conectando'), ('unpaired', 'Não pareado'), ('unpaired_idle', 'Não pareado (ocioso)'), ('unknown', 'Desconhecido')], default='unknown', max_length=20)),
                ('qrcode', models.TextField(blank=True, help_text='QR Code para conectar (base64)', null=True)),
                ('qrcode_url', models.URLField(blank=True, help_text='URL do QR Code', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Número de telefone conectado', max_length=20, null=True)),
                ('phone_name', models.CharField(blank=True, help_text='Nome do WhatsApp conectado', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Instância está ativa e sendo usada')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Última sincronização com Evolution API', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados adicionais da instância')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instância Evolution (Nova Arquitetura)',
                'verbose_name_plural': 'Instâncias Evolution (Nova Arquitetura)',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text="Tipo de evento (ex: 'messages.upsert', 'qrcode.updated')", max_length=50)),
                ('raw_payload', models.JSONField(help_text='Payload completo recebido da Evolution API')),
                ('processed', models.BooleanField(db_index=True, default=False, help_text='Evento foi processado')),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro se processamento falhou', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('instance', models.ForeignKey(help_text='Instância que recebeu o evento', on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='app_whatsapp_gateway.evolutioninstance')),
            ],
            options={
                'verbose_name': 'Evento Webhook Evolution',
                'verbose_name_plural': 'Eventos Webhook Evolution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='evolutioninstance',
            index=models.Index(fields=['shopper_id', 'status'], name='app_whatsap_shopper_4a3f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='evolutioninstance',
            index=models.Index(fields=['instance_id'], name='app_whatsap_instanc_8f5e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='evolutioninstance',
            index=models.Index(fields=['is_active', '-created_at'], name='app_whatsap_is_acti_9c7d4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evolutioninstance',
            unique_together={('shopper_id', 'instance_id')},
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['instance', '-created_at'], name='app_whatsap_instanc_2d8f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type', '-created_at'], name='app_whatsap_event__3e9f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['processed', '-created_at'], name='app_whatsap_process_4f8a9b_idx'),
        ),
    ]

