# Generated by Django 4.2.27 on 2026-01-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_whatsapp_gateway', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evolutioninstance',
            new_name='app_whatsap_shopper_ae6284_idx',
            old_name='app_whatsap_shopper_4a3f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='evolutioninstance',
            new_name='app_whatsap_instanc_d51eec_idx',
            old_name='app_whatsap_instanc_8f5e3a_idx',
        ),
        migrations.RenameIndex(
            model_name='evolutioninstance',
            new_name='app_whatsap_is_acti_eafdaf_idx',
            old_name='app_whatsap_is_acti_9c7d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='app_whatsap_instanc_d1c900_idx',
            old_name='app_whatsap_instanc_2d8f5e_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='app_whatsap_event_t_f6b551_idx',
            old_name='app_whatsap_event__3e9f7a_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='app_whatsap_process_656329_idx',
            old_name='app_whatsap_process_4f8a9b_idx',
        ),
        migrations.AlterField(
            model_name='evolutioninstance',
            name='status',
            field=models.CharField(choices=[('creating', 'Criando'), ('opening', 'Abrindo'), ('open', 'Conectada'), ('close', 'Desconectada'), ('connecting', 'Conectando'), ('unpaired', 'Não pareado'), ('unpaired_idle', 'Não pareado (ocioso)'), ('unknown', 'Desconhecido')], default='unknown', help_text='Status atual da instância', max_length=20),
        ),
    ]
