# Generated by Django 4.2.27 on 2026-01-06 04:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeScore',
            fields=[
                ('variant_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('creative_id', models.CharField(db_index=True, max_length=128)),
                ('product_id', models.CharField(db_index=True, max_length=128)),
                ('channel', models.CharField(db_index=True, max_length=32)),
                ('strategy', models.CharField(db_index=True, max_length=64)),
                ('response_rate', models.FloatField(default=0.0)),
                ('interest_rate', models.FloatField(default=0.0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('confidence_index', models.FloatField(default=0.0)),
                ('total_views', models.IntegerField(default=0)),
                ('total_responses', models.IntegerField(default=0)),
                ('total_interests', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_conversions', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'creative_score',
                'ordering': ['-engagement_score'],
                'indexes': [models.Index(fields=['product_id', 'channel'], name='creative_sc_product_27e0a0_idx'), models.Index(fields=['strategy', 'engagement_score'], name='creative_sc_strateg_9df5dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreativePerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_id', models.CharField(db_index=True, max_length=128)),
                ('creative_id', models.CharField(db_index=True, max_length=128)),
                ('product_id', models.CharField(db_index=True, max_length=128)),
                ('shopper_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'creative_performance',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant_id', 'event_type'], name='creative_pe_variant_4d32e1_idx'), models.Index(fields=['product_id', 'shopper_id'], name='creative_pe_product_9f2c0e_idx'), models.Index(fields=['created_at'], name='creative_pe_created_4343c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreativeAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creative_id', models.CharField(db_index=True, max_length=128)),
                ('variant_id', models.CharField(db_index=True, max_length=128)),
                ('product_id', models.CharField(db_index=True, max_length=128)),
                ('shopper_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('channel', models.CharField(db_index=True, max_length=32)),
                ('strategy', models.CharField(db_index=True, max_length=64)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('text_short', models.TextField(blank=True, null=True)),
                ('text_medium', models.TextField(blank=True, null=True)),
                ('text_long', models.TextField(blank=True, null=True)),
                ('discourse', models.JSONField(blank=True, default=dict)),
                ('ctas', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'creative_asset',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['creative_id', 'variant_id'], name='creative_as_creativ_92fc96_idx'), models.Index(fields=['product_id', 'shopper_id'], name='creative_as_product_0d80b6_idx'), models.Index(fields=['channel', 'strategy'], name='creative_as_channel_ad6f84_idx')],
            },
        ),
    ]
