# Generated by Django 4.2.27 on 2025-12-08 06:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_registro', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(max_length=100)),
                ('familia_olfativa', models.CharField(blank=True, max_length=100, null=True)),
                ('volume_ml', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('imagens', models.JSONField(blank=True, default=list, help_text='Lista de nomes de arquivos de imagens do produto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['marca', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shopper',
                'verbose_name_plural': 'Shoppers',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ServicoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome identificador do serviço (ex: Twilio Principal, Firebase Prod)', max_length=200)),
                ('tipo_servico', models.CharField(choices=[('twilio', 'Twilio'), ('sendgrid', 'SendGrid'), ('telegram', 'Telegram Bot API'), ('whatsapp', 'WhatsApp Business API'), ('aws', 'AWS'), ('azure', 'Azure'), ('google', 'Google Cloud'), ('firebase', 'Firebase'), ('digitalocean', 'DigitalOcean'), ('linode', 'Linode'), ('interserver', 'InterServer'), ('godaddy', 'GoDaddy'), ('namecheap', 'Namecheap'), ('hostgator', 'HostGator'), ('bluehost', 'Bluehost'), ('hostinger', 'Hostinger'), ('siteground', 'SiteGround'), ('dreamhost', 'DreamHost'), ('vultr', 'Vultr'), ('hetzner', 'Hetzner'), ('contabo', 'Contabo'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mercadopago', 'Mercado Pago'), ('facebook', 'Facebook API'), ('instagram', 'Instagram API'), ('openai', 'OpenAI'), ('outro', 'Outro')], default='outro', help_text='Tipo de serviço contratado', max_length=50)),
                ('ambiente', models.CharField(choices=[('desenvolvimento', 'Desenvolvimento'), ('homologacao', 'Homologação'), ('producao', 'Produção')], default='desenvolvimento', help_text='Ambiente de uso do serviço', max_length=20)),
                ('url_base', models.URLField(blank=True, help_text='URL base do serviço (ex: https://api.twilio.com)', max_length=500, null=True)),
                ('usuario', models.CharField(blank=True, help_text='Usuário/Login para autenticação', max_length=200, null=True)),
                ('senha', models.TextField(blank=True, help_text='Senha/Token de autenticação (armazenado de forma criptografada)', null=True)),
                ('api_key', models.CharField(blank=True, help_text='API Key do serviço', max_length=500, null=True)),
                ('api_secret', models.TextField(blank=True, help_text='API Secret (armazenado de forma criptografada)', null=True)),
                ('account_sid', models.CharField(blank=True, help_text='Account SID (para serviços como Twilio)', max_length=200, null=True)),
                ('auth_token', models.TextField(blank=True, help_text='Auth Token (armazenado de forma criptografada)', null=True)),
                ('ip_servidor', models.GenericIPAddressField(blank=True, help_text='Endereço IP do servidor VPS', null=True)),
                ('porta_ssh', models.IntegerField(blank=True, default=22, help_text='Porta SSH do servidor (padrão: 22)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('usuario_ssh', models.CharField(blank=True, help_text='Usuário SSH para acesso ao servidor', max_length=100, null=True)),
                ('senha_ssh', models.TextField(blank=True, help_text='Senha SSH (armazenado de forma criptografada)', null=True)),
                ('chave_privada_ssh', models.TextField(blank=True, help_text='Chave privada SSH (armazenado de forma criptografada)', null=True)),
                ('url_painel_controle', models.URLField(blank=True, help_text='URL do painel de controle (cPanel, Plesk, etc)', max_length=500, null=True)),
                ('usuario_painel', models.CharField(blank=True, help_text='Usuário do painel de controle', max_length=200, null=True)),
                ('senha_painel', models.TextField(blank=True, help_text='Senha do painel de controle (armazenado de forma criptografada)', null=True)),
                ('sistema_operacional', models.CharField(blank=True, help_text='Sistema operacional do servidor (ex: Ubuntu 22.04, CentOS 7)', max_length=100, null=True)),
                ('porta_ftp', models.IntegerField(blank=True, default=21, help_text='Porta FTP (padrão: 21)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('usuario_ftp', models.CharField(blank=True, help_text='Usuário FTP', max_length=100, null=True)),
                ('senha_ftp', models.TextField(blank=True, help_text='Senha FTP (armazenado de forma criptografada)', null=True)),
                ('porta_mysql', models.IntegerField(blank=True, default=3306, help_text='Porta MySQL/MariaDB (padrão: 3306)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('usuario_mysql', models.CharField(blank=True, help_text='Usuário do banco de dados MySQL', max_length=100, null=True)),
                ('senha_mysql', models.TextField(blank=True, help_text='Senha do banco de dados MySQL (armazenado de forma criptografada)', null=True)),
                ('nome_banco_dados', models.CharField(blank=True, help_text='Nome do banco de dados', max_length=100, null=True)),
                ('credenciais_adicionais', models.JSONField(blank=True, default=dict, help_text='Credenciais adicionais em formato JSON (ex: project_id, database_url, domain, etc)')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o serviço está ativo e sendo usado')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o serviço e credenciais', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço Externo',
                'verbose_name_plural': 'Serviços Externos',
                'ordering': ['tipo_servico', 'ambiente', 'nome'],
                'unique_together': {('tipo_servico', 'ambiente', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_compra_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('preco_compra_brl', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('margem_lucro_percentual', models.DecimalField(decimal_places=2, help_text='Margem de lucro em percentual', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('preco_venda_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('preco_venda_brl', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_viagem', to='app_sinapum.campanha')),
                ('estabelecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_viagem', to='app_sinapum.estabelecimento')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produto_viagem', to='app_sinapum.produto')),
                ('shopper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_viagem', to='app_sinapum.shopper')),
            ],
            options={
                'verbose_name': 'Produto Viagem',
                'verbose_name_plural': 'Produtos Viagem',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_json', models.JSONField(help_text='Dados completos do produto no formato modelo.json')),
                ('nome_produto', models.CharField(db_index=True, help_text='Nome do produto para busca rápida', max_length=500)),
                ('marca', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('codigo_barras', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('imagem_original', models.CharField(blank=True, help_text='Nome do arquivo de imagem original', max_length=500, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto JSON',
                'verbose_name_plural': 'Produtos JSON',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['nome_produto', 'marca'], name='app_sinapum_nome_pr_6b7b1d_idx'), models.Index(fields=['categoria'], name='app_sinapum_categor_6add47_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProdutoGenericoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(max_length=100)),
                ('variantes', models.JSONField(blank=True, default=list, help_text="Lista de variantes do produto (ex: ['50ml', 'Parfum'])")),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto Genérico do Catálogo',
                'verbose_name_plural': 'Produtos Genéricos do Catálogo',
                'ordering': ['marca', 'nome'],
                'unique_together': {('nome', 'marca', 'categoria', 'subcategoria')},
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='produto_generico',
            field=models.ForeignKey(blank=True, help_text='Produto genérico relacionado ao catálogo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app_sinapum.produtogenericocatalogo'),
        ),
        migrations.CreateModel(
            name='CadastroMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capturado_por', models.CharField(help_text='Sistema/IA que capturou os dados', max_length=200)),
                ('data_captura', models.DateTimeField()),
                ('fonte', models.TextField(help_text='Fonte dos dados (ex: Fotos tiradas na loja)')),
                ('confianca_da_leitura', models.DecimalField(decimal_places=2, help_text='Confiança da leitura (0.0 a 1.0)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('detalhes_rotulo', models.JSONField(blank=True, default=dict, help_text='Detalhes do rótulo (frase, origem, duração, etc)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cadastro_meta', to='app_sinapum.produto')),
            ],
            options={
                'verbose_name': 'Cadastro Meta',
                'verbose_name_plural': 'Cadastros Meta',
                'ordering': ['-data_captura'],
            },
        ),
    ]
