# Generated by Django 4.2.27 on 2025-12-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sinapum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicoexterno',
            name='tipo_servico',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('sendgrid', 'SendGrid'), ('telegram', 'Telegram Bot API'), ('whatsapp', 'WhatsApp Business API'), ('aws', 'AWS'), ('azure', 'Azure'), ('google', 'Google Cloud'), ('firebase', 'Firebase'), ('railway', 'Railway'), ('digitalocean', 'DigitalOcean'), ('linode', 'Linode'), ('interserver', 'InterServer'), ('godaddy', 'GoDaddy'), ('namecheap', 'Namecheap'), ('hostgator', 'HostGator'), ('bluehost', 'Bluehost'), ('hostinger', 'Hostinger'), ('siteground', 'SiteGround'), ('dreamhost', 'DreamHost'), ('vultr', 'Vultr'), ('hetzner', 'Hetzner'), ('contabo', 'Contabo'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mercadopago', 'Mercado Pago'), ('facebook', 'Facebook API'), ('instagram', 'Instagram API'), ('openai', 'OpenAI'), ('outro', 'Outro')], default='outro', help_text='Tipo de serviço contratado', max_length=50),
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome identificador único do prompt (ex: 'analise_produto_v1')", max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do que este prompt faz e quando deve ser usado', null=True)),
                ('tipo_prompt', models.CharField(choices=[('analise_imagem_produto', 'Análise de Imagem de Produto'), ('extracao_json', 'Extração de JSON'), ('classificacao_categoria', 'Classificação de Categoria'), ('processamento_texto', 'Processamento de Texto'), ('traducao', 'Tradução'), ('resumo', 'Resumo'), ('outro', 'Outro')], default='outro', help_text='Tipo/categoria do prompt', max_length=50)),
                ('prompt_text', models.TextField(help_text='Texto completo do prompt que será enviado para a IA')),
                ('versao', models.CharField(default='1.0', help_text="Versão do prompt (ex: '1.0', '1.1', '2.0')", max_length=20)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se este prompt está ativo e pode ser usado pelos serviços')),
                ('eh_padrao', models.BooleanField(default=False, help_text='Indica se este é o prompt padrão para o tipo. Apenas um prompt por tipo pode ser padrão.')),
                ('parametros', models.JSONField(blank=True, default=dict, help_text='Parâmetros/configurações adicionais em formato JSON (ex: temperatura, max_tokens, etc)')),
                ('exemplos', models.TextField(blank=True, help_text='Exemplos de uso ou outputs esperados', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o prompt, mudanças recentes, testes realizados, etc', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Prompt',
                'verbose_name_plural': 'Templates de Prompts',
                'ordering': ['tipo_prompt', '-eh_padrao', '-versao', 'nome'],
                'indexes': [models.Index(fields=['tipo_prompt', 'ativo', 'eh_padrao'], name='app_sinapum_tipo_pr_ea4f13_idx'), models.Index(fields=['nome'], name='app_sinapum_nome_4f7169_idx')],
            },
        ),
    ]
