# Generated by Django 4.2.27 on 2025-12-16 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sinapum', '0002_alter_servicoexterno_tipo_servico_prompttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome do sistema/aplicativo (ex: 'MotoPro', 'VitrineZap', 'Évora')", max_length=100, unique=True)),
                ('codigo', models.CharField(help_text="Código único do sistema (ex: 'motopro', 'vitrinezap', 'evora') - usado para identificação programática", max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do sistema e seu propósito', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o sistema está ativo e em uso')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o sistema', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='sistema',
            field=models.ForeignKey(blank=True, help_text='Sistema/aplicativo ao qual este prompt pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='app_sinapum.sistema'),
        ),
        migrations.RemoveIndex(
            model_name='prompttemplate',
            name='app_sinapum_nome_4f7169_idx',
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='nome',
            field=models.CharField(help_text="Nome identificador do prompt (ex: 'analise_produto_v1')", max_length=200),
        ),
        migrations.AlterModelOptions(
            name='prompttemplate',
            options={'ordering': ['sistema', 'tipo_prompt', '-eh_padrao', '-versao', 'nome'], 'verbose_name': 'Template de Prompt', 'verbose_name_plural': 'Templates de Prompts'},
        ),
        migrations.AddIndex(
            model_name='sistema',
            index=models.Index(fields=['codigo', 'ativo'], name='app_sinapum_codigo_9ab4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='sistema',
            index=models.Index(fields=['nome'], name='app_sinapum_nome_8b39ce_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['sistema', 'tipo_prompt', 'ativo', 'eh_padrao'], name='app_sinapum_sistema_609cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['sistema', 'nome'], name='app_sinapum_sistema_c8e9b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prompttemplate',
            unique_together={('sistema', 'nome')},
        ),
    ]
