# Generated by Django 4.2.27 on 2026-01-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlagConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Nome da feature flag', max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='Se flag está globalmente habilitada')),
                ('shadow_mode', models.BooleanField(default=False, help_text='Se flag está em shadow mode (não interfere no fluxo)')),
                ('allowlist', models.JSONField(blank=True, default=list, help_text='Lista de shopper_ids habilitados (JSON array)')),
                ('denylist', models.JSONField(blank=True, default=list, help_text='Lista de shopper_ids bloqueados (JSON array)')),
                ('percent_rollout', models.IntegerField(default=0, help_text='Percentual de rollout (0-100)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados adicionais (JSON object)')),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Se configuração está ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Usuário que criou a flag', max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, help_text='Usuário que atualizou a flag', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Feature Flag Config',
                'verbose_name_plural': 'Feature Flag Configs',
                'db_table': 'core_feature_flag_config',
                'indexes': [models.Index(fields=['name', 'active'], name='core_featur_name_d58231_idx'), models.Index(fields=['active', 'enabled'], name='core_featur_active_90b032_idx')],
            },
        ),
    ]
