# Generated by Django 4.2.27 on 2026-01-06 04:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppWhatsappInstance',
            fields=[
                ('instance_key', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('provider', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('created', 'Created'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('closed', 'Closed')], db_index=True, default='created', max_length=32)),
                ('last_qr', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Instance',
                'verbose_name_plural': 'WhatsApp Instances',
                'db_table': 'app_whatsapp_instance',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status'], name='app_whatsap_provide_932bec_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppWhatsappEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('instance_key', models.CharField(db_index=True, max_length=128)),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('shopper_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'WhatsApp Event',
                'verbose_name_plural': 'WhatsApp Events',
                'db_table': 'app_whatsapp_event',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['instance_key', 'ts'], name='app_whatsap_instanc_547cb5_idx'), models.Index(fields=['provider', 'type'], name='app_whatsap_provide_35e8f1_idx'), models.Index(fields=['shopper_id', 'ts'], name='app_whatsap_shopper_7db135_idx')],
            },
        ),
    ]
