# Generated by Django 4.2.27 on 2026-01-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_whatsapp_events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='whatsappconversation',
            new_name='app_whatsap_last_ev_fdc8c7_idx',
            old_name='app_whatsap_last_eve_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappconversation',
            new_name='app_whatsap_status_fb941b_idx',
            old_name='app_whatsap_status__idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappconversation',
            new_name='app_whatsap_shopper_ea2e8d_idx',
            old_name='app_whatsap_conv_shopper_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappconversation',
            new_name='app_whatsap_skm_id_3d429c_idx',
            old_name='app_whatsap_conv_skm_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappeventlog',
            new_name='app_whatsap_thread__4cdc9d_idx',
            old_name='app_whatsap_thread__idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappeventlog',
            new_name='app_whatsap_provide_f063f8_idx',
            old_name='app_whatsap_provider_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappeventlog',
            new_name='app_whatsap_occurre_fcbf7f_idx',
            old_name='app_whatsap_occurre_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappeventlog',
            new_name='app_whatsap_event_t_f6fd53_idx',
            old_name='app_whatsap_event_t_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappeventlog',
            new_name='app_whatsap_provide_6cc2c2_idx',
            old_name='app_whatsap_provide_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappeventlog',
            new_name='app_whatsap_convers_0c744e_idx',
            old_name='app_whatsap_events_conv_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappeventlog',
            new_name='app_whatsap_shopper_b919bf_idx',
            old_name='app_whatsap_events_shopper_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappeventlog',
            new_name='app_whatsap_skm_id_e7a941_idx',
            old_name='app_whatsap_events_skm_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessageindex',
            new_name='app_whatsap_convers_206de5_idx',
            old_name='app_whatsap_msg_conv_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessageindex',
            new_name='app_whatsap_directi_9bc9b2_idx',
            old_name='app_whatsap_msg_dir_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappthreadparticipant',
            new_name='app_whatsap_role_46625b_idx',
            old_name='app_whatsap_role_las_idx',
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['thread_key'], name='app_whatsap_thread__1ab791_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappeventlog',
            index=models.Index(fields=['idempotency_key'], name='app_whatsap_idempot_73425a_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessageindex',
            index=models.Index(fields=['provider_message_id'], name='app_whatsap_provide_51363c_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappthreadparticipant',
            index=models.Index(fields=['conversation', 'wa_id'], name='app_whatsap_convers_2552c1_idx'),
        ),
    ]
