# Generated by Django 4.2.27 on 2026-01-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='app_convers_shopper_2296b6_idx',
            old_name='app_convers_shopper_5a8f3d_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='app_convers_convers_24b407_idx',
            old_name='app_convers_convers_9c7d4e_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='app_convers_custome_4dbdb0_idx',
            old_name='app_convers_custome_2f8a9b_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='app_convers_owner_b218b5_idx',
            old_name='app_convers_owner__3e9f7a_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='app_convers_convers_0f66f8_idx',
            old_name='app_convers_convers_4f8a9b_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='app_convers_directi_c13d3b_idx',
            old_name='app_convers_direct_5a8f3d_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='app_convers_sent_by_f5c66d_idx',
            old_name='app_convers_sent_by_6c9e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='suggestion',
            new_name='app_convers_convers_1833a4_idx',
            old_name='app_convers_convers_7d9f5e_idx',
        ),
        migrations.RenameIndex(
            model_name='suggestion',
            new_name='app_convers_status_ea1342_idx',
            old_name='app_convers_status__8e0f6a_idx',
        ),
        migrations.RenameIndex(
            model_name='suggestion',
            new_name='app_convers_intent_c0f32d_idx',
            old_name='app_convers_intent__9f1g7b_idx',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='chat_type',
            field=models.CharField(choices=[('private', 'Privada'), ('group', 'Grupo')], default='private', help_text='Tipo de chat', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='mode',
            field=models.CharField(choices=[('assistido', 'Assistido'), ('auto', 'Automático')], default='assistido', help_text='Modo de operação (IA sugere vs IA envia direto)', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='owner',
            field=models.CharField(choices=[('AI', 'IA'), ('SHOPPER', 'Shopper')], default='AI', help_text='Quem está gerenciando a conversa', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída')], help_text='Direção da mensagem', max_length=3),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('file', 'Arquivo'), ('interactive', 'Interativo'), ('unknown', 'Desconhecido')], default='text', help_text='Tipo de mensagem', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_by',
            field=models.CharField(choices=[('customer', 'Cliente'), ('ai', 'IA'), ('shopper', 'Shopper'), ('system', 'Sistema')], default='customer', help_text='Quem enviou a mensagem', max_length=10),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('dismissed', 'Descartada')], db_index=True, default='pending', help_text='Status da sugestão', max_length=10),
        ),
    ]
