# Generated by Django 4.2.27 on 2025-12-24 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ifood_integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ifoodsyncrun',
            new_name='ifood_sync__store_i_ab7e85_idx',
            old_name='ifood_sync_store_k_idx',
        ),
        migrations.RenameIndex(
            model_name='ifoodsyncrun',
            new_name='ifood_sync__ok_cf35cf_idx',
            old_name='ifood_sync_ok_start_idx',
        ),
        migrations.RenameIndex(
            model_name='mrfooorder',
            new_name='mrfoo_order_store_i_7d6549_idx',
            old_name='mrfoo_ord_store_cre_idx',
        ),
        migrations.RenameIndex(
            model_name='mrfooorder',
            new_name='mrfoo_order_status_abab2a_idx',
            old_name='mrfoo_ord_status_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='mrfooorder',
            new_name='mrfoo_order_channel_02b322_idx',
            old_name='mrfoo_ord_chan_cre_idx',
        ),
        migrations.RenameIndex(
            model_name='mrfoopayout',
            new_name='mrfoo_payou_store_i_753af8_idx',
            old_name='mrfoo_pay_store_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='mrfoopayout',
            new_name='mrfoo_payou_channel_42e7d4_idx',
            old_name='mrfoo_pay_chan_ref_idx',
        ),
    ]
