# Generated by Django 4.2.27 on 2026-01-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='app_leads_l_email_0eaf02_idx',
            old_name='app_leads_l_email_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='app_leads_l_whatsap_77891c_idx',
            old_name='app_leads_l_whatsap_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='app_leads_l_source__f25734_idx',
            old_name='app_leads_l_source__idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='app_leads_l_created_23d3cd_idx',
            old_name='app_leads_lead_created_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='app_leads_l_lead_st_190ffa_idx',
            old_name='app_leads_lead_status_idx',
        ),
        migrations.RenameIndex(
            model_name='leadevent',
            new_name='app_leads_l_lead_id_0710c4_idx',
            old_name='app_leads_event_lead_idx',
        ),
        migrations.RenameIndex(
            model_name='leadevent',
            new_name='app_leads_l_event_t_38e214_idx',
            old_name='app_leads_event_type_idx',
        ),
        migrations.RenameIndex(
            model_name='leadevent',
            new_name='app_leads_l_created_d55227_idx',
            old_name='app_leads_event_created_idx',
        ),
        migrations.RenameIndex(
            model_name='projectcredential',
            new_name='app_leads_p_project_7ecc74_idx',
            old_name='app_leads_p_project__idx',
        ),
        migrations.RenameIndex(
            model_name='projectcredential',
            new_name='app_leads_p_is_acti_7cb5ea_idx',
            old_name='app_leads_p_is_acti_idx',
        ),
    ]
