# Generated by Django 4.2.27 on 2026-05-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sinapcore', '0008_pricing_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pricinglog',
            new_name='app_sinapco_empresa_e30e41_idx',
            old_name='app_sinapco_empresa_8f3a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='pricinglog',
            new_name='app_sinapco_produto_eed920_idx',
            old_name='app_sinapco_produto_2c9e4d_idx',
        ),
    ]
