# Generated by Django 4.2.27 on 2026-03-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_canonicaleventlog_alter_simulatedmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonicaleventlog',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Payload específico do evento'),
        ),
        migrations.AlterField(
            model_name='canonicaleventlog',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Payload bruto do provider'),
        ),
    ]
