# Generated by Django migration
# Migration inicial para app_mcp_tool_registry

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('api_key', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client App',
                'verbose_name_plural': 'Client Apps',
                'db_table': 'mcp_client_app',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'db_table': 'mcp_tool',
            },
        ),
        migrations.CreateModel(
            name='ToolVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('input_schema', models.JSONField(default=dict)),
                ('output_schema', models.JSONField(default=dict)),
                ('runtime', models.CharField(choices=[('noop', 'Noop'), ('prompt', 'Prompt'), ('openmind_http', 'OpenMind HTTP'), ('pipeline', 'Pipeline'), ('ddf', 'DDF')], default='noop', max_length=40)),
                ('config', models.JSONField(default=dict)),
                ('prompt_ref', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app_mcp_tool_registry.tool')),
            ],
            options={
                'verbose_name': 'Tool Version',
                'verbose_name_plural': 'Tool Versions',
                'db_table': 'mcp_tool_version',
                'unique_together': {('tool', 'version')},
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='allowed_clients',
            field=models.ManyToManyField(blank=True, to='app_mcp_tool_registry.clientapp'),
        ),
        migrations.AddField(
            model_name='tool',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app_mcp_tool_registry.toolversion'),
        ),
        migrations.CreateModel(
            name='ToolCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('tool', models.CharField(max_length=160)),
                ('version', models.CharField(max_length=30)),
                ('client_key', models.CharField(blank=True, max_length=80)),
                ('ok', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(default=200)),
                ('latency_ms', models.IntegerField(default=0)),
                ('input_payload', models.JSONField(blank=True, null=True)),
                ('output_payload', models.JSONField(blank=True, null=True)),
                ('error_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tool Call Log',
                'verbose_name_plural': 'Tool Call Logs',
                'db_table': 'mcp_tool_call_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='toolcalllog',
            index=models.Index(fields=['request_id'], name='mcp_tool_c_request_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcalllog',
            index=models.Index(fields=['tool', 'version'], name='mcp_tool_c_tool_ve_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcalllog',
            index=models.Index(fields=['created_at'], name='mcp_tool_c_created_idx'),
        ),
    ]

