# Generated by Django 4.2.27 on 2025-12-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mcp_tool_registry', '0002_add_trace_id_to_tool_call_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='toolcalllog',
            new_name='mcp_tool_ca_request_125292_idx',
            old_name='mcp_tool_c_request_idx',
        ),
        migrations.RenameIndex(
            model_name='toolcalllog',
            new_name='mcp_tool_ca_trace_i_881998_idx',
            old_name='mcp_tool_c_trace_i_idx',
        ),
        migrations.RenameIndex(
            model_name='toolcalllog',
            new_name='mcp_tool_ca_tool_4d3d1f_idx',
            old_name='mcp_tool_c_tool_ve_idx',
        ),
        migrations.RenameIndex(
            model_name='toolcalllog',
            new_name='mcp_tool_ca_created_0ab1c9_idx',
            old_name='mcp_tool_c_created_idx',
        ),
    ]
