"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-^_*fwd08xsh)gnlcpq8ggpj3br9+2=$6qno@r_fjcr=0*g!w4^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

# ALLOWED_HOSTS - suporta variável de ambiente para Docker
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',')]
else:
    ALLOWED_HOSTS = ['69.169.102.84', 'localhost', '127.0.0.1', 'web', '0.0.0.0']


# ============================================================================
# Feature Flags - Nova Arquitetura WhatsApp
# ============================================================================
FEATURE_EVOLUTION_MULTI_TENANT = os.environ.get('FEATURE_EVOLUTION_MULTI_TENANT', 'False').lower() in ('true', '1', 'yes')
FEATURE_OPENMIND_ENABLED = os.environ.get('FEATURE_OPENMIND_ENABLED', 'False').lower() in ('true', '1', 'yes')
FEATURE_CONSOLE_ENABLED = os.environ.get('FEATURE_CONSOLE_ENABLED', 'False').lower() in ('true', '1', 'yes')

# Evolution API - Nova Arquitetura
EVOLUTION_BASE_URL = os.environ.get('EVOLUTION_BASE_URL', 'http://69.169.102.84:8004')
EVOLUTION_API_KEY = os.environ.get('EVOLUTION_API_KEY', 'GKvy6psn-8HHpBQ4HAHKFOXnwjHR-oSzeGZzCaws0xg')
EVOLUTION_TIMEOUT = int(os.environ.get('EVOLUTION_TIMEOUT', '30'))

# WhatsApp Gateway - Provider Selection
WHATSAPP_PROVIDER = os.environ.get('WHATSAPP_PROVIDER', 'simulated')  # simulated|cloud|baileys|evolution

# OpenMind AI - Nova Arquitetura
OPENMIND_BASE_URL = os.environ.get('OPENMIND_BASE_URL', 'http://69.169.102.84:8001')
OPENMIND_TOKEN = os.environ.get('OPENMIND_TOKEN', '')

# VitrineZap API - Para MCP Tools
# NOTA: Évora/VitrineZap está no Railway, não no servidor SinapUm
VITRINEZAP_BASE_URL = os.environ.get('VITRINEZAP_BASE_URL', 'https://evora-product.up.railway.app')
INTERNAL_API_TOKEN = os.environ.get('INTERNAL_API_TOKEN', '')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework
    'app_sinapum',
    'app_mcp_tool_registry',
    'app_ifood_integration',
    'app_leads',  # Lead Registry - Sistema central de captação
    # ============================================================================
    # ARQUITETURA NOVA - WhatsApp Gateway Multi-tenant
    # ============================================================================
    'app_whatsapp_gateway',  # Gateway Evolution multi-tenant (legado)
    'app_whatsapp',  # WhatsApp Gateway plugável (nova arquitetura)
    'app_creative_engine',  # Creative Engine - Motor de criativos
    'app_conversations',  # Conversas e sugestões de IA
    'app_ai_bridge',  # Ponte com OpenMind
    'app_mcp',  # Tools MCP para IA
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise para servir arquivos estáticos
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'setup' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

from urllib.parse import urlparse

# Configuração do banco - SEMPRE PostgreSQL
# Usar variáveis de ambiente ou valores padrão
DATABASE_URL = os.environ.get('DATABASE_URL', '')

if DATABASE_URL:
    # Usar PostgreSQL via DATABASE_URL
    parsed = urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path[1:],  # Remove a barra inicial
            'USER': parsed.username,
            'PASSWORD': parsed.password,
            'HOST': parsed.hostname or os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': parsed.port or os.environ.get('POSTGRES_PORT', '5432'),
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }
else:
    # PostgreSQL usando variáveis de ambiente individuais
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'mcp_sinapum'),
            'USER': os.environ.get('POSTGRES_USER', 'mcp_user'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'mcp_password_change_me'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Diretório onde collectstatic vai coletar os arquivos

# Diretórios adicionais para arquivos estáticos (opcional)
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Se houver um diretório static na raiz
]

# WhiteNoise para servir arquivos estáticos em produção
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
# Usar /data/vitrinezap/images/ para imagens do VitrineZap
# Fallback para media/ local se /data não estiver disponível
VITRINEZAP_IMAGES_PATH = Path('/data/vitrinezap/images')
if VITRINEZAP_IMAGES_PATH.exists():
    MEDIA_ROOT = VITRINEZAP_IMAGES_PATH
    # Criar subdiretório uploads se não existir
    (MEDIA_ROOT / 'uploads').mkdir(parents=True, exist_ok=True)
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# OpenMind AI Configuration
OPENMIND_AI_URL = os.environ.get('OPENMIND_AI_URL', 'http://127.0.0.1:8001')
OPENMIND_AI_KEY = os.environ.get('OPENMIND_AI_KEY', 'om1_live_7d4102a1bf72cc497d7651beb6a98292764b1f77df947c82d086506038ea6b9921efb9d9833045d1')

# CrewAI Configuration (para orquestração de agentes)
# IMPORTANTE: O CrewAI usa OpenMind.org como backend LLM!
# OpenMind.org oferece acesso a múltiplos modelos (OpenAI, Anthropic, Gemini, etc.)
# através de uma API unificada, usando a mesma chave do OpenMind AI.
CREWAI_CONFIG = {
    'default_llm': 'openmind',  # Usa OpenMind.org como backend
    'temperature': 0.7,
    'max_iterations': 3,
}

# OpenMind.org Configuration (para CrewAI LLM backend)
# Usa a MESMA chave do OpenMind AI - não precisa de chaves separadas!
OPENMIND_ORG_BASE_URL = 'https://api.openmind.org/api/core/openai'
OPENMIND_ORG_API_KEY = OPENMIND_AI_KEY  # Mesma chave!
OPENMIND_ORG_MODEL = 'gpt-4o'  # Pode ser: claude-3-opus, gemini-pro, etc.

# OpenAI API Key (fallback, caso não use OpenMind.org)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# Agnos Configuration (para orquestração de alto nível)
AGNOS_CONFIG = {
    'enabled': True,  # Habilitar quando Agnos estiver disponível
    'default_workflow': 'analise_completa_produto',
    'state_persistence': True,
    'state_backend': 'memory',  # ou 'redis', 'database'
    'max_concurrent_crews': 3,
    'timeout': 300,  # segundos
}

# Sistema Configuration (para identificação do sistema/aplicativo)
# Usado para buscar prompts do PostgreSQL (PromptTemplate) por sistema
# Valores possíveis: 'evora', 'vitrinezap', 'motopro', etc.
# Deve corresponder ao campo 'codigo' do modelo Sistema em app_sinapum.models
SISTEMA_CODIGO = os.environ.get('SISTEMA_CODIGO', 'evora')

# ============================================================================
# HTTPS / SSL Configuration
# ============================================================================
# Quando usar Nginx como proxy reverso, o Django detecta HTTPS através do
# header X-Forwarded-Proto enviado pelo Nginx.
# 
# IMPORTANTE: Django/Gunicorn NÃO serve HTTPS diretamente.
# Use Nginx como proxy reverso para terminar SSL/TLS.
# ============================================================================

# Django confia no header X-Forwarded-Proto do proxy reverso (Nginx)
# Isso permite que Django saiba que está atrás de HTTPS mesmo recebendo HTTP interno
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Não fazer redirect aqui (Nginx já faz redirect HTTP → HTTPS)
# Se True, Django tentaria fazer redirect, mas Nginx já faz isso
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() in ('true', '1', 'yes')

# Cookies seguros (apenas via HTTPS)
# Em desenvolvimento ou HTTP, desabilitar para permitir cookies
# Em produção com HTTPS, habilitar via variável de ambiente
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False').lower() in ('true', '1', 'yes')
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() in ('true', '1', 'yes')

# HSTS (HTTP Strict Transport Security)
# Força navegadores a usar HTTPS por 1 ano
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))  # 1 ano
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() in ('true', '1', 'yes')
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'True').lower() in ('true', '1', 'yes')

# Outras configurações de segurança
SECURE_CONTENT_TYPE_NOSNIFF = os.environ.get('SECURE_CONTENT_TYPE_NOSNIFF', 'True').lower() in ('true', '1', 'yes')
SECURE_BROWSER_XSS_FILTER = os.environ.get('SECURE_BROWSER_XSS_FILTER', 'True').lower() in ('true', '1', 'yes')
X_FRAME_OPTIONS = os.environ.get('X_FRAME_OPTIONS', 'DENY')  # 'DENY', 'SAMEORIGIN', ou 'ALLOWALL'

# Nota: Em desenvolvimento (DEBUG=True), algumas dessas configurações podem ser relaxadas
# para facilitar o desenvolvimento. Em produção, todas devem estar ativas.

# Prompt Registry Configuration
# Integração entre PromptTemplate (PostgreSQL) e ToolVersion.prompt_ref (MCP Tool Registry)
# O campo prompt_ref no ToolVersion pode referenciar:
# - Nome do PromptTemplate (ex: "analise_produto_v1")
# - Sistema.codigo + PromptTemplate.nome (ex: "evora:analise_produto_v1")
# - Sistema.codigo + PromptTemplate.tipo_prompt (ex: "evora:analise_imagem_produto")
PROMPT_REF_FORMAT = os.environ.get('PROMPT_REF_FORMAT', 'sistema:nome')  # 'nome', 'sistema:nome', 'sistema:tipo'

# MCP Tool Registry Configuration
# Limite máximo de tamanho de input em bytes (padrão: 10MB)
MCP_MAX_INPUT_BYTES = int(os.environ.get('MCP_MAX_INPUT_BYTES', 10485760))  # 10MB

# DDF Service Configuration (para runtime ddf)
DDF_BASE_URL = os.environ.get('DDF_BASE_URL', 'http://ddf_service:8005')
DDF_TIMEOUT = int(os.environ.get('DDF_TIMEOUT', 60))  # segundos

# MCP Service Configuration (para delegação opcional)
MCP_SERVICE_URL = os.environ.get('MCP_SERVICE_URL', 'http://mcp_service:7010')

# Evolution API Configuration (WhatsApp Integration)
# Detectar automaticamente se está em container ou host
# Em container Docker: usar 'http://evolution_api:8080'
# No host: usar 'http://127.0.0.1:8004'
import socket
try:
    # Tentar resolver 'evolution_api' (só funciona dentro da rede Docker)
    socket.gethostbyname('evolution_api')
    DEFAULT_EVOLUTION_API_URL = 'http://evolution_api:8080'
except socket.gaierror:
    # Se não conseguir resolver, estamos no host
    DEFAULT_EVOLUTION_API_URL = 'http://127.0.0.1:8004'

EVOLUTION_API_URL = os.environ.get('EVOLUTION_API_URL', DEFAULT_EVOLUTION_API_URL)
EVOLUTION_API_KEY = os.environ.get('EVOLUTION_API_KEY', 'GKvy6psn-8HHpBQ4HAHKFOXnwjHR-oSzeGZzCaws0xg')
EVOLUTION_INSTANCE_NAME = os.environ.get('EVOLUTION_INSTANCE_NAME', 'core_sinapum')
