"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^_*fwd08xsh)gnlcpq8ggpj3br9+2=$6qno@r_fjcr=0*g!w4^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['69.169.102.84', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_sinapum',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
# Usar /data/vitrinezap/images/ para imagens do VitrineZap
# Fallback para media/ local se /data não estiver disponível
import os
VITRINEZAP_IMAGES_PATH = Path('/data/vitrinezap/images')
if VITRINEZAP_IMAGES_PATH.exists():
    MEDIA_ROOT = VITRINEZAP_IMAGES_PATH
    # Criar subdiretório uploads se não existir
    (MEDIA_ROOT / 'uploads').mkdir(parents=True, exist_ok=True)
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# OpenMind AI Configuration
OPENMIND_AI_URL = 'http://127.0.0.1:8000'
OPENMIND_AI_KEY = 'om1_live_7d4102a1bf72cc497d7651beb6a98292764b1f77df947c82d086506038ea6b9921efb9d9833045d1'

# CrewAI Configuration (para orquestração de agentes)
# IMPORTANTE: O CrewAI usa OpenMind.org como backend LLM!
# OpenMind.org oferece acesso a múltiplos modelos (OpenAI, Anthropic, Gemini, etc.)
# através de uma API unificada, usando a mesma chave do OpenMind AI.
CREWAI_CONFIG = {
    'default_llm': 'openmind',  # Usa OpenMind.org como backend
    'temperature': 0.7,
    'max_iterations': 3,
}

# OpenMind.org Configuration (para CrewAI LLM backend)
# Usa a MESMA chave do OpenMind AI - não precisa de chaves separadas!
OPENMIND_ORG_BASE_URL = 'https://api.openmind.org/api/core/openai'
OPENMIND_ORG_API_KEY = OPENMIND_AI_KEY  # Mesma chave!
OPENMIND_ORG_MODEL = 'gpt-4o'  # Pode ser: claude-3-opus, gemini-pro, etc.

# OpenAI API Key (fallback, caso não use OpenMind.org)
import os
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# Agnos Configuration (para orquestração de alto nível)
AGNOS_CONFIG = {
    'enabled': True,  # Habilitar quando Agnos estiver disponível
    'default_workflow': 'analise_completa_produto',
    'state_persistence': True,
    'state_backend': 'memory',  # ou 'redis', 'database'
    'max_concurrent_crews': 3,
    'timeout': 300,  # segundos
}
